name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'   # Runs once daily at midnight UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run User Statistician
        uses: cicirello/user-statistician@v1
        with:
          user: ojaswi1234
          output: output   # Folder where SVGs will be saved

      - name: Commit and Push Stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.svg
          git commit -m "Update GitHub stats"
          git push
